import type { NextPage } from "next";
import Head from "next/head";
import { PokemonList } from "../components/PokemonList";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PokemonList />
      </main>
    </div>
  );
};

export default Home;
