import type { NextPage } from "next";
import Head from "next/head";
import { Suspense } from "react";
import { ClientOnly } from "../components/ClientOnly";
import { PokemonList } from "../components/PokemonList";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h2>Server-side suspense</h2>
          <Suspense fallback={<p>Loading...</p>}>
            <PokemonList />
          </Suspense>
        </div>
        <div>
          <h2>Client-side suspense</h2>
          <ClientOnly>
            <Suspense fallback={<p>Loading...</p>}>
              <PokemonList />
            </Suspense>
          </ClientOnly>
        </div>
      </main>
    </div>
  );
};

export default Home;
